spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/isupayx
spring.datasource.username=root
spring.datasource.password=Subha@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true